name: release

on :
  push :
    tags :
      - '*'

permissions:
  contents: write

jobs:
    buildTest: 
        uses: adrrf/decide_practica3_2324/.github/workflows/django.yml@main
        secrets: CODACY_PROJECT_TOKEN: ${{ secret.CODACY_PROJECT_TOKEN }}
    
    release:
        needs: buildTest
        runs-on: ubuntu-latest
        steps:
            -name: Checkout
            uses: actions/checkout@v3
            -name: Release
            uses: softprops/action-gh-release@v1